# Welcome to Jekyll!

# Site settings
title: Jedidah Wavinya Portfolio
email: wavinyajedidah@gmail.com
description: >-
  I am a passionate and detail-oriented ICT professional with a background in Mathematics and Computer Science. 
  I have hands-on experience in data analysis, digital marketing, and software support, and I enjoy solving real-world problems using technology. 
  I'm always eager to learn, collaborate, and grow in roles that combine creativity, logic, and impact.
twitter_username: username
github_username: jedidahwavinya

# Theme settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: mint
search: true

# Build settings
markdown: kramdown

# Output settings
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone:

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author settings
author:
  name: "Jedidah Wavinya"
  avatar: "/assets/images/OLE_0058.jpg"
  bio: "Data analyst, Digital Marketer, and Tech Enthusiast."
  links:
    #- label: "Website"
    # icon: "fas fa-fw fa-link"
     # url: "https://"
    - label: "LinkedIn"
      icon:  "fab fa-fw fa-linkedin"
      url: "www.linkedin.com/in/jedidahwavinya"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jedidahwavinya"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/_.wavinya._"

# Footer links
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jedidahwavinya"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/_.wavinya._"

# Defaults for posts and pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
